# Generated by Django 4.1 on 2022-09-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('serialNumber', models.IntegerField(max_length=255)),
                ('countInStock', models.IntegerField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('model', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('planes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.planes')),
            ],
        ),
        migrations.CreateModel(
            name='faultyPart',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.parts')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.planes')),
            ],
        ),
    ]
