# Generated by Django 4.1 on 2022-09-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultypart',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.parts'),
        ),
        migrations.AlterField(
            model_name='faultypart',
            name='plane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.planes'),
        ),
        migrations.AlterField(
            model_name='operators',
            name='planes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.planes'),
        ),
    ]
