# Generated by Django 4.1 on 2022-09-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_parts_countinstock_alter_parts_serialnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operators',
            name='planes',
        ),
        migrations.AddField(
            model_name='operators',
            name='planes',
            field=models.ManyToManyField(to='base.planes'),
        ),
    ]
